### ISSUE TITLE
认证服务不可用,请稍后再试，或联系管理员。Authenicaton service unavailable

### ISSUE THREAD

**Issue by oasisgallagher97** [SaltfishAmi/seu-covid-dailyReport#4]
请问有什么方法解决

**Comment by SaltfishAmi** [comment]
Could you please provide a screenshot?

请发张截图给我看看好吗？

**Comment by oasisgallagher97** [comment]
> Could you please provide a screenshot?
> 
> 请发张截图给我看看好吗？

![Uploading Snipaste_2020-11-25_00-20-32.png…]()

**Comment by oasisgallagher97** [comment]
> Could you please provide a screenshot?
> 
> 请发张截图给我看看好吗？

![Snipaste_2020-11-25_00-20-32](https://user-images.githubusercontent.com/20724645/100122595-8416a680-2eb4-11eb-8bd0-a2aeffc9b8a0.png)

**Comment by oasisgallagher97** [comment]
> > Could you please provide a screenshot?
> > 请发张截图给我看看好吗？
> 
> chrome和firefox都是这样

**Comment by SaltfishAmi** [comment]
This script only automates the login and reporting process. It has nothing special, and does not communicate with any server other that the campus servers. So I feel like this is a problem related to the campus servers. Try switching to campus internet (seu-wlan) if you are not already using it, or give it another shot tomorrow morning after the NIC starts their office hours. The last thing to do is sending message to your grade president and tell him/her that the school network system is shit. I’ve done this already.

我这个脚本只是自动化登陆和上报的动作，没什么特殊的，也没有和任何其他服务器通信，因此我感觉是服务器问题，如果是外网的话试试用校园网，或者等明天信息中心上班了再试试，再不行就给你们辅导员发消息说学校的系统是垃圾。今年三四月份有段时间这个服务器每到晚上十二点就关闭，这也是我做这个脚本的直接原因。

**Comment by oasisgallagher97** [comment]
> This script only automates the login and reporting process. It has nothing special, and does not communicate with any server other that the campus servers. So I feel like this is a problem related to the campus servers. Try switching to campus internet (seu-wlan) if you are not already using it, or give it another shot tomorrow morning after the NIC starts their office hours. The last thing to do is sending message to your grade president and tell him/her that the school network system is shit. I’ve done this already.
> 
> 我这个脚本只是自动化登陆和上报的动作，没什么特殊的，也没有和任何其他服务器通信，因此我感觉是服务器问题，如果是外网的话试试用校园网，或者等明天信息中心上班了再试试，再不行就给你们辅导员发消息说学校的系统是垃圾。今年三四月份有段时间这个服务器每到晚上十二点就关闭，这也是我做这个脚本的直接原因。

我一个室友是可以正常使用的，另一个室友和我是同样的问题，比较好奇，我明天上午再试试，谢谢回复

**Comment by SaltfishAmi** [comment]
As long as you follow the instructions (use the link I provided as entry point), you should get the same result using the script as if you log in and report completely manually.

如果遵守使用方法（使用我提供的链接进入登陆），使用脚本和完全手动操作登陆上报应该得到一样的结果

**Comment by oasisgallagher97** [comment]
今天上午尝试登录成功，应该是服务器问题
