### ISSUE TITLE
NOT Wuhan pneumonia

### ISSUE THREAD

**Issue by XAKK** [SaltfishAmi/seu-covid-dailyReport#5]
Hi, I noticed you mention  Wuhan pneumoniathe at your script discription. Plz use its right name AKA COVID-19.

**Comment by SaltfishAmi** [comment]
I’m not succumbing to political correctness no matter it’s western or eastern. Just like I’m not getting rid of the ‘master’ branch name, I’ll not change this.

**Comment by SaltfishAmi** [comment]
I’ll use the correct name COVID-19 in any new text (you may already noticed this), but there is no reason I should censor the history with nowadays common sense.
